import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { FileEdit, Download } from 'lucide-react';

const NOTICE_TYPES = [
  { id: 'rental', label: 'Rental Dispute' },
  { id: 'money', label: 'Money Recovery' },
  { id: 'consumer', label: 'Consumer Complaint' },
];

const NOTICES: Record<string, string> = {
  rental: `LEGAL NOTICE

Date: ${new Date().toLocaleDateString()}

To,
[Landlord Name]
[Address]

Subject: Notice for Illegal Eviction and Refund of Security Deposit

Dear Sir/Madam,

Under instructions from my client, [Tenant Name], residing at [Address], I hereby serve upon you the following legal notice:

1. That my client has been a tenant of the premises at [Address] since [Date] and has been regularly paying rent of ₹[Amount] per month.

2. That you have illegally demanded the premises to be vacated without providing the statutory notice period of [X] months as per the Rent Control Act.

3. That you have failed to refund the security deposit of ₹[Amount] despite repeated requests.

4. That you are hereby called upon to refund the security deposit within 15 days and provide adequate notice period for vacation of premises.

5. Failing which, my client shall be constrained to initiate appropriate legal proceedings before the competent court, at your risk and cost.

Yours faithfully,
[Advocate Name]
[Enrollment No.]`,

  money: `LEGAL NOTICE FOR RECOVERY OF MONEY

Date: ${new Date().toLocaleDateString()}

To,
[Debtor Name]
[Address]

Subject: Demand for Repayment of Outstanding Loan Amount

Under instructions from my client, [Creditor Name], I serve this legal notice:

1. That my client advanced a sum of ₹[Amount] to you on [Date] based on mutual trust and your promise to repay within [Period].

2. That despite the expiry of the agreed repayment period and repeated oral and written reminders, you have failed to repay the said amount.

3. That your conduct amounts to breach of trust and cheating under Sections 403 and 420 of IPC.

4. You are hereby called upon to repay the full amount of ₹[Amount] along with interest at the rate of [X]% per annum within 15 days.

5. Failing which, my client shall file both civil and criminal proceedings against you.

Yours faithfully,
[Advocate Name]`,

  consumer: `CONSUMER COMPLAINT NOTICE

Date: ${new Date().toLocaleDateString()}

To,
[Company/Seller Name]
[Address]

Subject: Defective Product / Deficiency in Service – Consumer Protection Act, 2019

Dear Sir/Madam,

My client, [Consumer Name], purchased [Product/Service] from your [Store/Platform] on [Date] vide Invoice No. [Number].

1. The said product/service has been found defective/deficient as [describe defect].

2. Despite bringing this to your notice on [Date], no satisfactory resolution has been provided.

3. Under Section 2(6) of the Consumer Protection Act, 2019, this constitutes unfair trade practice / deficiency in service.

4. You are hereby directed to [replace/refund/repair] within 15 days.

5. Failure to do so will compel my client to file a complaint before the Consumer Disputes Redressal Forum.

Yours faithfully,
[Advocate Name]`,
};

export default function DraftNotice() {
  const [type, setType] = useState('');
  const [generated, setGenerated] = useState(false);

  const handleDownload = () => {
    const blob = new Blob([NOTICES[type]], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `legal-notice-${type}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in space-y-6">
      <div className="glass-card-gold p-4">
        <h2 className="font-serif text-xl font-bold">Draft Legal Notice Generator</h2>
        <p className="text-sm text-muted-foreground">Select a notice type to generate a formatted draft.</p>
      </div>

      {!generated ? (
        <div className="space-y-4">
          <div className="grid md:grid-cols-3 gap-4">
            {NOTICE_TYPES.map(n => (
              <button key={n.id} onClick={() => setType(n.id)} className={`glass-card p-5 text-center transition-all ${type === n.id ? 'border-electric glow-electric' : 'hover:border-electric/30'}`}>
                <FileEdit className="w-8 h-8 mx-auto mb-2 text-gold" />
                <h3 className="font-serif font-semibold">{n.label}</h3>
              </button>
            ))}
          </div>
          <Button onClick={() => type && setGenerated(true)} disabled={!type} className="w-full gradient-electric glow-electric">Generate Notice</Button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="border-gold/40 text-gold">Draft Generated by AI – Prototype Simulation</Badge>
            <Button onClick={handleDownload} variant="ghost" size="sm" className="text-electric"><Download className="w-4 h-4 mr-1" />Download</Button>
          </div>
          <div className="glass-card p-6">
            <pre className="text-sm text-muted-foreground whitespace-pre-wrap font-sans leading-relaxed">{NOTICES[type]}</pre>
          </div>
          <Button variant="ghost" onClick={() => { setGenerated(false); setType(''); }}>← Choose Another Type</Button>
        </div>
      )}
    </div>
  );
}
